import datetime

from suse_cloud_image_name_parser.suse_cloud_image_name import (
    SUSECloudImageName
)


class TestSUSECloudImageName(object):

    def test_suse_cloud_image_name(self):

        test_cases = [
            (
                "021d1b90c82943ec959408cff8e26c37__suse-manager-server-5-0-byos-v20250729-x86_64",  # NOQA
                {
                    'is_x86_64': True,
                    'is_aarch64': False,
                    'is_arm64': False,
                    'is_amd64': True,
                    'is_leap': False,
                    'is_sle_server': False,
                    'is_sle': False,
                    'is_suma': True,
                    'suma_type': 'server',
                    'is_sap': False,
                    'is_byos': True,
                    'is_payg': False,
                    'is_tomcat': False,
                    'is_postgresql': False,
                    'is_php': False,
                    'is_mariadb': False,
                    'is_basic': False,
                    'product_major_int': 5,
                    'product_minor_int': 0,
                    'product_version': '5.0',
                    'distro_version': '5.5',
                    'has_uuid_prefix': True,
                    'is_chost': False,
                    'is_hardened': False,
                    'is_micro': False,
                    'is_ssd': False,
                    'is_ltd': None,
                    'is_llc': None,
                    'is_containerized': True,
                    'created_at': datetime.datetime(2025, 7, 29),
                    'oval_product': 'suse.linux.enterprise.micro.5.5',
                    'short_name': 'suma',
                    'is_sles_plus_foo': False,
                }
            ),
            (
                "suse-sles-15-sp7-hardened-byos-v20250619-hvm-ssd-x86_64",
                {
                    'is_x86_64': True,
                    'is_aarch64': False,
                    'is_arm64': False,
                    'is_amd64': True,
                    'is_leap': False,
                    'is_sle_server': True,
                    'is_sle': False,
                    'is_suma': False,
                    'suma_type': None,
                    'is_sap': False,
                    'is_byos': True,
                    'is_payg': False,
                    'is_tomcat': False,
                    'is_postgresql': False,
                    'is_php': False,
                    'is_mariadb': False,
                    'is_basic': False,
                    'product_major_int': 15,
                    'product_minor_int': 7,
                    'product_version': '15-SP7',
                    'distro_version': '15-SP7',
                    'has_uuid_prefix': False,
                    'is_chost': False,
                    'is_hardened': True,
                    'is_micro': False,
                    'is_ssd': True,
                    'is_ltd': None,
                    'is_llc': None,
                    'is_containerized': False,
                    'created_at': datetime.datetime(2025, 6, 19),
                    'oval_product': 'suse.linux.enterprise.15',
                    'short_name': 'sles',
                    'is_sles_plus_foo': False,
                }
            ),
            (
                "suse-sle-micro-5-3-v20250724-hvm-ssd-arm64-ltd",
                {
                    'is_x86_64': False,
                    'is_aarch64': True,
                    'is_arm64': True,
                    'is_amd64': False,
                    'is_leap': False,
                    'is_sle_server': False,
                    'is_sle': True,
                    'is_suma': False,
                    'suma_type': None,
                    'is_sap': False,
                    'is_byos': False,
                    'is_payg': True,
                    'is_tomcat': False,
                    'is_postgresql': False,
                    'is_php': False,
                    'is_mariadb': False,
                    'is_basic': False,
                    'product_major_int': 5,
                    'product_minor_int': 3,
                    'product_version': '5.3',
                    'distro_version': '15-SP4',
                    'has_uuid_prefix': False,
                    'is_chost': False,
                    'is_hardened': False,
                    'is_micro': True,
                    'is_ssd': True,
                    'is_ltd': True,
                    'is_llc': False,
                    'is_containerized': False,
                    'created_at': datetime.datetime(2025, 7, 24),
                    'oval_product': 'suse.linux.enterprise.micro.5.3',
                    'short_name': 'SLE-Micro',
                    'is_sles_plus_foo': False,
                }
            ),
            (
                "suse-sle-micro-6-0-v20250724-hvm-ssd-arm64-ltd",
                {
                    'is_x86_64': False,
                    'is_aarch64': True,
                    'is_arm64': True,
                    'is_amd64': False,
                    'is_leap': False,
                    'is_sle_server': False,
                    'is_sle': True,
                    'is_suma': False,
                    'suma_type': None,
                    'is_sap': False,
                    'is_byos': False,
                    'is_payg': True,
                    'is_tomcat': False,
                    'is_postgresql': False,
                    'is_php': False,
                    'is_mariadb': False,
                    'is_basic': False,
                    'product_major_int': 6,
                    'product_minor_int': 0,
                    'product_version': '6.0',
                    'distro_version': 'SL-Framework-One',
                    'has_uuid_prefix': False,
                    'is_chost': False,
                    'is_hardened': False,
                    'is_micro': True,
                    'is_ssd': True,
                    'is_ltd': True,
                    'is_llc': False,
                    'is_containerized': False,
                    'created_at': datetime.datetime(2025, 7, 24),
                    'oval_product': 'suse.linux.micro.6.0',
                    'short_name': 'SL-Micro',
                    'is_sles_plus_foo': False,
                }
            ),
            (
                "suse-sles-16-0-chost-byos-v20250725-hvm-ssd-x86_64",
                {
                    'is_x86_64': True,
                    'is_aarch64': False,
                    'is_arm64': False,
                    'is_amd64': True,
                    'is_leap': False,
                    'is_sle_server': True,
                    'is_sle': False,
                    'is_suma': False,
                    'suma_type': None,
                    'is_sap': False,
                    'is_byos': True,
                    'is_payg': False,
                    'is_tomcat': False,
                    'is_postgresql': False,
                    'is_php': False,
                    'is_mariadb': False,
                    'is_basic': False,
                    'product_major_int': 16,
                    'product_minor_int': 0,
                    'product_version': '16.0',
                    'distro_version': '16.0',
                    'has_uuid_prefix': False,
                    'is_chost': True,
                    'is_hardened': False,
                    'is_micro': False,
                    'is_ssd': True,
                    'is_ltd': None,
                    'is_llc': None,
                    'is_containerized': False,
                    'created_at': datetime.datetime(2025, 7, 25),
                    'oval_product': 'suse.linux.enterprise.16',
                    'short_name': 'sles',
                    'is_sles_plus_foo': False,
                }
            ),
            (
                "openSUSE-Leap-15-6-v20250725-hvm-ssd-arm64",
                {
                    'is_x86_64': False,
                    'is_aarch64': True,
                    'is_arm64': True,
                    'is_amd64': False,
                    'is_leap': True,
                    'is_sle_server': False,
                    'is_sle': False,
                    'is_suma': False,
                    'suma_type': None,
                    'is_sap': False,
                    'is_byos': False,
                    'is_payg': False,
                    'is_tomcat': False,
                    'is_postgresql': False,
                    'is_php': False,
                    'is_mariadb': False,
                    'is_basic': False,
                    'product_major_int': 15,
                    'product_minor_int': 6,
                    'product_version': '15.6',
                    'distro_version': '15.6',
                    'has_uuid_prefix': False,
                    'is_chost': False,
                    'is_hardened': False,
                    'is_micro': False,
                    'is_ssd': True,
                    'is_ltd': None,
                    'is_llc': None,
                    'is_containerized': False,
                    'created_at': datetime.datetime(2025, 7, 25),
                    'oval_product': 'opensuse.leap.15.6',
                    'short_name': 'OPENSUSE-LEAP',
                    'is_sles_plus_foo': False,
                }
            ),
            (
                "suse-sles-16-0-tomcat-v20250101-hvm-ssd-x86_64-llc",
                {
                    'is_x86_64': True,
                    'is_aarch64': False,
                    'is_arm64': False,
                    'is_amd64': True,
                    'is_leap': False,
                    'is_sle_server': True,
                    'is_sle': False,
                    'is_suma': False,
                    'suma_type': None,
                    'is_sap': False,
                    'is_byos': False,
                    'is_payg': True,
                    'is_tomcat': True,
                    'is_postgresql': False,
                    'is_php': False,
                    'is_mariadb': False,
                    'is_basic': False,
                    'product_major_int': 16,
                    'product_minor_int': 0,
                    'product_version': '16.0',
                    'distro_version': '16.0',
                    'has_uuid_prefix': False,
                    'is_chost': False,
                    'is_hardened': False,
                    'is_micro': False,
                    'is_ssd': True,
                    'is_ltd': False,
                    'is_llc': True,
                    'is_containerized': False,
                    'created_at': datetime.datetime(2025, 1, 1),
                    'oval_product': 'suse.linux.enterprise.16',
                    'short_name': 'sles',
                    'is_sles_plus_foo': True,
                }
            ),
            (
                "suse-sles-16-0-php-v20250101-hvm-ssd-x86_64-llc",
                {
                    'is_x86_64': True,
                    'is_aarch64': False,
                    'is_arm64': False,
                    'is_amd64': True,
                    'is_leap': False,
                    'is_sle_server': True,
                    'is_sle': False,
                    'is_suma': False,
                    'suma_type': None,
                    'is_sap': False,
                    'is_byos': False,
                    'is_payg': True,
                    'is_tomcat': False,
                    'is_postgresql': False,
                    'is_php': True,
                    'is_mariadb': False,
                    'is_basic': False,
                    'product_major_int': 16,
                    'product_minor_int': 0,
                    'product_version': '16.0',
                    'distro_version': '16.0',
                    'has_uuid_prefix': False,
                    'is_chost': False,
                    'is_hardened': False,
                    'is_micro': False,
                    'is_ssd': True,
                    'is_ltd': False,
                    'is_llc': True,
                    'is_containerized': False,
                    'created_at': datetime.datetime(2025, 1, 1),
                    'oval_product': 'suse.linux.enterprise.16',
                    'short_name': 'sles',
                    'is_sles_plus_foo': True,
                }
            ),
            (
                "suse-sles-16-0-mariadb-v20250101-hvm-ssd-x86_64-llc",
                {
                    'is_x86_64': True,
                    'is_aarch64': False,
                    'is_arm64': False,
                    'is_amd64': True,
                    'is_leap': False,
                    'is_sle_server': True,
                    'is_sle': False,
                    'is_suma': False,
                    'suma_type': None,
                    'is_sap': False,
                    'is_byos': False,
                    'is_payg': True,
                    'is_tomcat': False,
                    'is_postgresql': False,
                    'is_php': False,
                    'is_mariadb': True,
                    'is_basic': False,
                    'product_major_int': 16,
                    'product_minor_int': 0,
                    'product_version': '16.0',
                    'distro_version': '16.0',
                    'has_uuid_prefix': False,
                    'is_chost': False,
                    'is_hardened': False,
                    'is_micro': False,
                    'is_ssd': True,
                    'is_ltd': False,
                    'is_llc': True,
                    'is_containerized': False,
                    'created_at': datetime.datetime(2025, 1, 1),
                    'oval_product': 'suse.linux.enterprise.16',
                    'short_name': 'sles',
                    'is_sles_plus_foo': True,
                }
            ),
            (
                "suse-sles-16-0-postgresql-v20250101-hvm-ssd-x86_64-llc",
                {
                    'is_x86_64': True,
                    'is_aarch64': False,
                    'is_arm64': False,
                    'is_amd64': True,
                    'is_leap': False,
                    'is_sle_server': True,
                    'is_sle': False,
                    'is_suma': False,
                    'suma_type': None,
                    'is_sap': False,
                    'is_byos': False,
                    'is_payg': True,
                    'is_tomcat': False,
                    'is_postgresql': True,
                    'is_php': False,
                    'is_mariadb': False,
                    'is_basic': False,
                    'product_major_int': 16,
                    'product_minor_int': 0,
                    'product_version': '16.0',
                    'distro_version': '16.0',
                    'has_uuid_prefix': False,
                    'is_chost': False,
                    'is_hardened': False,
                    'is_micro': False,
                    'is_ssd': True,
                    'is_ltd': False,
                    'is_llc': True,
                    'is_containerized': False,
                    'created_at': datetime.datetime(2025, 1, 1),
                    'oval_product': 'suse.linux.enterprise.16',
                    'short_name': 'sles',
                    'is_sles_plus_foo': True,
                }
            ),
            (
                "suse-manager-proxy-5-1-byos-v20250917-hvm-ssd-arm64",
                {
                    'is_x86_64': False,
                    'is_aarch64': True,
                    'is_arm64': True,
                    'is_amd64': False,
                    'is_leap': False,
                    'is_sle_server': False,
                    'is_sle': False,
                    'is_suma': True,
                    'suma_type': 'proxy',
                    'is_sap': False,
                    'is_byos': True,
                    'is_payg': False,
                    'is_tomcat': False,
                    'is_postgresql': False,
                    'is_php': False,
                    'is_mariadb': False,
                    'is_basic': False,
                    'product_major_int': 5,
                    'product_minor_int': 1,
                    'product_version': '5.1',
                    'distro_version': '6.1',
                    'has_uuid_prefix': False,
                    'is_chost': False,
                    'is_hardened': False,
                    'is_micro': False,
                    'is_ssd': True,
                    'is_ltd': None,
                    'is_llc': None,
                    'is_containerized': True,
                    'created_at': datetime.datetime(2025, 9, 17),
                    'oval_product': 'suse.linux.micro.6.1',
                    'short_name': 'multi-linux-manager-proxy',
                    'is_sles_plus_foo': False,
                }
            ),
            (
                "suse-manager-server-5-2-byos-v20250917-hvm-ssd-x86-64",
                {
                    'is_x86_64': True,
                    'is_aarch64': False,
                    'is_arm64': False,
                    'is_amd64': True,
                    'is_leap': False,
                    'is_sle_server': False,
                    'is_sle': False,
                    'is_suma': True,
                    'suma_type': 'server',
                    'is_sap': False,
                    'is_byos': True,
                    'is_payg': False,
                    'is_tomcat': False,
                    'is_postgresql': False,
                    'is_php': False,
                    'is_mariadb': False,
                    'is_basic': False,
                    'product_major_int': 5,
                    'product_minor_int': 2,
                    'product_version': '5.2',
                    'distro_version': '15-SP7',
                    'has_uuid_prefix': False,
                    'is_chost': False,
                    'is_hardened': False,
                    'is_micro': False,
                    'is_ssd': True,
                    'is_ltd': None,
                    'is_llc': None,
                    'is_containerized': True,
                    'created_at': datetime.datetime(2025, 9, 17),
                    'oval_product': 'suse.linux.enterprise.15-sp7',
                    'cloud_arch': 'x86_64',
                    'short_name': 'multi-linux-manager',
                    'is_sles_plus_foo': False,
                }
            ),
        ]

        for (image, expected_result) in test_cases:
            image_name = SUSECloudImageName(image)
            for key, value in expected_result.items():
                assert getattr(image_name, key) == value
